### PR TITLE
PR for #82,  #83 and #85

### PR DESCRIPTION
**Pull request by jborgers**
This PR solves:

#82. The same custom rule files appear more than once in the action menu

#83. Custom rules set menu items are not descriptive enough
 
#85 Configuration skipTestSources is not persisted and uses wrong default

### CODE REVIEW

**Comment by amitdev** [comment]
Thanks. For future, it is better to raise separate PRs for each issue. It makes it easier to test and review.

**Review by amitdev — APPROVED** [review]

**Comment by jborgers** [comment]
Yes. I was trying to make 2 PR's, however, somehow GitHub added them
together in one.
Not sure how to separate them properly.


Op zo 14 mrt. 2021 om 02:12 schreef Amit Dev ***@***.***>:

**Comment by jborgers** [comment]
Strange, in the new plugin in my intellij I see #82 solved, yet not #83 and #85. Is that intended?

**Comment by jborgers** [comment]
I see a new plugin version: 1.8.16 and it solves all three issues now :-)

**Pull request merged**
