### PR TITLE
Show annotations in editor, and allow quick-fix to surpress. Issue #134

### PR DESCRIPTION
**Pull request by martenbohlin**

### CODE REVIEW

**Comment by SoulOfSet** [comment]
Wild. Was just looking for this functionality. Great to know it's in the works. 👍  Thanks @martenbohlin

**Comment by sashokbg** [comment]
Hello how is this supposed to look ? I have the latest version and I don't see any "live coding" annotations for PMD :(

**Comment by SoulOfSet** [comment]
@sashokbg  This has been recently merged but I do not think it's been packaged for a release yet.

**Comment by sashokbg** [comment]
Hey @SoulOfSet thank you for your prompt answer. I propose we take the conversation to the issue page 
#134

**Pull request merged**
